### ISSUE TITLE
URL:Phishing

### ISSUE THREAD

**Issue by Drjacky** [MetaMask/phishing-warning#30]
<img width="638" alt="Screen Shot 2022-07-13 at 08 49 58" src="https://user-images.githubusercontent.com/2296754/178680228-857fec77-4358-4954-b7de-6161ec7e9d72.png">

**Comment by Gudahtt** [comment]
Thanks for the report!

We noticed this a few weeks back and contacted Avast about removing this false positive. Let us know if this is still blocked.
